-- MySQL Script generated by MySQL Workbench
-- Tue May 28 01:51:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgec` DEFAULT CHARACTER SET utf8mb4 ;
USE `sgec` ;

-- -----------------------------------------------------
-- Table `sgec`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgec`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgec`.`espaços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgec`.`espaços` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL,
  `endereco` TEXT NOT NULL,
  `descricao` TEXT NOT NULL,
  `capacidade` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_espaços_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_espaços_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sgec`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
